//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSede.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int id_evento { get; set; }
        public Nullable<int> id_complejo { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> duracion { get; set; }
        public Nullable<int> num_participante { get; set; }
        public Nullable<int> num_comisario { get; set; }
        public string tipo { get; set; }
    
        public virtual Sede_Complejo Sede_Complejo { get; set; }
    }
}
