//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSede.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede_Complejo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sede_Complejo()
        {
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int id_complejo { get; set; }
        public Nullable<int> id_sede { get; set; }
        public string tipo_sede { get; set; }
        public string nombre { get; set; }
        public string area { get; set; }
        public string localizacion { get; set; }
        public string Jefe_organizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventos> Eventos { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
